[package]
name = "greenery-rust"
version = "0.1.0"
authors = ["Evan Logsdon <logsdonevan1@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
rust-s3 = "0.22.12"
chrono = "0.4"